### ISSUE TITLE
🐛 [24.10.30] 분리한 api 호출부 서버사이드 환경에서의 window 객체 정의 관련 #157

### ISSUE THREAD

**Issue by s-ja** [Mt-NextJs/linkle#187]
### 개발 서버 터미널 에러 출력
```bash
 ⨯ src/utils/apis/index.ts (121:20) @ getInstance
 ⨯ unhandledRejection: ReferenceError: window is not defined
    at getInstance (webpack-internal:///(ssr)/./src/utils/apis/index.ts:110:23)
    at eval (webpack-internal:///(ssr)/./src/utils/apis/index.ts:116:26)
    at (ssr)/./src/utils/apis/index.ts (/Users/seungjian/Documents/development/sniper_project/project/.next/server/app/login/page.js:193:1)
    at __webpack_require__ (/Users/seungjian/Documents/development/sniper_project/project/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(ssr)/./src/app/login/page.tsx:15:69)
    at (ssr)/./src/app/login/page.tsx (/Users/seungjian/Documents/development/sniper_project/project/.next/server/app/login/page.js:149:1)
    at Object.__webpack_require__ [as require] (/Users/seungjian/Documents/development/sniper_project/project/.next/server/webpack-runtime.js:33:42)
    at require (/Users/seungjian/Documents/development/sniper_project/project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:19799)
    at u (/Users/seungjian/Documents/development/sniper_project/project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:97669)
    at /Users/seungjian/Documents/development/sniper_project/project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:113238
    at /Users/seungjian/Documents/development/sniper_project/project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:113325
    at /Users/seungjian/Documents/development/sniper_project/project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:113485
    at /Users/seungjian/Documents/development/sniper_project/project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:115235
    at t (/Users/seungjian/Documents/development/sniper_project/project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:115458)
  119 |   if (!type) return new Apis();
  120 |   if (type === "block") {
> 121 |     const token = `${window.sessionStorage.getItem("token")}`;
      |                    ^
  122 |     const sequence = (await getSequence(token)) || 0;
  123 |     return new adminApis(token, sequence);
  124 |   }
 GET /login 200 in 87ms
```
## 재현 가능 여부

- [x] 예
- [ ] 아니오

### 예상 수정 필요 코드
```
const getInstance = async (type?: string) => {
  if (!type) return new Apis();
  if (type === "block") {
    const token = `${window.sessionStorage.getItem("token")}`;
    const sequence = (await getSequence(token)) || 0;
    return new adminApis(token, sequence);
  }
  if (type === "auth") return new AuthApis();
};
```
- 위 코드에서 window 객체 존재 시에만 sessionStorage에 접근하도록 조건문을 추가 혹은
- 토큰을 파라미터로 전달하도록 getInstance 함수 수정, 서버와 클라이언트 모두에서 사용할 수 있도록 조정

**Comment by lumpenop** [comment]
#190 과 같은 이슈라서 닫겠습니다..!
